// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeAxfUIJcCvguT40L-qFKGK15qWhKangY',
    appId: '1:248349843239:web:88ecb3137742c15f705302',
    messagingSenderId: '248349843239',
    projectId: 'kyro-wk9',
    authDomain: 'kyro-wk9.firebaseapp.com',
    storageBucket: 'kyro-wk9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFyAyJX9wdswDQnicAoXM57SHrtougNd4',
    appId: '1:248349843239:android:6178f7249284afd1705302',
    messagingSenderId: '248349843239',
    projectId: 'kyro-wk9',
    storageBucket: 'kyro-wk9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_tb7cXwd-Tl0MFZ7H2i74AUhpzqDmi_A',
    appId: '1:248349843239:ios:fd7679b228653d43705302',
    messagingSenderId: '248349843239',
    projectId: 'kyro-wk9',
    storageBucket: 'kyro-wk9.appspot.com',
    iosBundleId: 'com.example.wk9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_tb7cXwd-Tl0MFZ7H2i74AUhpzqDmi_A',
    appId: '1:248349843239:ios:fd7679b228653d43705302',
    messagingSenderId: '248349843239',
    projectId: 'kyro-wk9',
    storageBucket: 'kyro-wk9.appspot.com',
    iosBundleId: 'com.example.wk9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeAxfUIJcCvguT40L-qFKGK15qWhKangY',
    appId: '1:248349843239:web:df836604d507cd5b705302',
    messagingSenderId: '248349843239',
    projectId: 'kyro-wk9',
    authDomain: 'kyro-wk9.firebaseapp.com',
    storageBucket: 'kyro-wk9.appspot.com',
  );

}